name: tempcastrnn
channels:
  - defaults
  - pytorch
  - conda-forge

dependencies:
  - python=3.10
  - pytorch>=1.13
  - torchvision
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - tqdm
  - requests
  - ipykernel
  - notebook